server:
  port: 8082
spring:
  application:
    name: my-second-service
eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: ${server.address}
#    instance-id: ${server.address}:${server.port}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

